INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget]) VALUES (N'Dehradun', 100, 10000)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget]) VALUES (N'Jammu', 350, 20000)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget]) VALUES (N'Kashmir', 350, 20000)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget]) VALUES (N'Mussorie', 150, 13000)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget]) VALUES (N'Shimla', 250, 15000)
