SET IDENTITY_INSERT [dbo].[Datas] ON
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Dehradun', 100, 10000, N'Riverside', N'Adventure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Dehradun', 100, 10000, N'Riverside', N'Adventure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 2)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Mussorie', 150, 13000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 3)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Mussorie', 150, 13000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 4)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Shimla', 250, 15000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Shimla', 250, 15000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 6)
INSERT INTO [dbo].[Datas] ([Location], [Dfd], [Budget], [AccdName], [AccdTypePreferenceOrder1], [AccdTypePreferenceOrder2], [AccdTypePreferenceOrder3], [AccdTypePreferenceOrder4], [PtvName], [PtvTypePreferenceOrder1], [PtvTypePreferenceOrder2], [PtvTypePreferenceOrder3], [PtvTypePreferenceOrder4], [Id]) VALUES (N'Shimla', 250, 15000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 7)
SET IDENTITY_INSERT [dbo].[Datas] ON
